# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Swift_login' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Swift_login

  target 'Swift_loginTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Swift_loginUITests' do
    # Pods for testing
  end

pod "Alamofire"

end
